"""Exact inference architecture extracted from the final Stage-2 notebook.

Do not edit this file unless the training architecture itself changes.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import timm
import torch
import torch.nn as nn
import torch.nn.functional as F


@dataclass
class Stage2Config:
    img_size: int = 224
    patch_size: int = 16
    vit_name: str = "vit_base_patch16_224"
    embed_dim: int = 768
    patch_grid: int = 14
    spatial_target: int = 16
    proj_channels: int = 192
    num_classes: int = 9


def xavier_init(module: nn.Module) -> None:
    if isinstance(module, nn.Linear):
        nn.init.xavier_uniform_(module.weight)
        if module.bias is not None:
            nn.init.zeros_(module.bias)


class ViTEncoder(nn.Module):
    def __init__(self, model_name: str, dropout: float = 0.1):
        super().__init__()
        self.vit = timm.create_model(model_name, pretrained=False, num_classes=0)
        self.embed_dim = self.vit.num_features
        self.num_prefix_tokens = getattr(self.vit, "num_prefix_tokens", 1)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        tokens = self.vit.forward_features(x)
        tokens = tokens[:, self.num_prefix_tokens :, :]
        return self.dropout(tokens)


class CBABlock(nn.Module):
    def __init__(self, dim: int, num_heads: int = 8, dropout: float = 0.1):
        super().__init__()
        self.conv = nn.Conv1d(dim, dim, kernel_size=3, padding=1)
        self.norm1 = nn.LayerNorm(dim)
        self.attn = nn.MultiheadAttention(
            dim, num_heads=num_heads, dropout=dropout, batch_first=True
        )
        self.norm2 = nn.LayerNorm(dim)
        self.drop = nn.Dropout(dropout)
        self.apply(xavier_init)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        residual = x
        conv_features = self.conv(x.transpose(1, 2)).transpose(1, 2)
        x = self.norm1(residual + self.drop(conv_features))
        attention_features, _ = self.attn(x, x, x, need_weights=False)
        return self.norm2(x + self.drop(attention_features))


class SpatialBridge(nn.Module):
    def __init__(self, embed_dim: int, proj_channels: int, patch_grid: int, target_size: int):
        super().__init__()
        self.patch_grid = patch_grid
        self.target_size = target_size
        self.proj = nn.Conv2d(embed_dim, proj_channels, kernel_size=1)
        self.bn = nn.BatchNorm2d(proj_channels)
        self.act = nn.GELU()

    def forward(self, tokens: torch.Tensor) -> torch.Tensor:
        batch_size, token_count, embed_dim = tokens.shape
        expected_tokens = self.patch_grid**2
        if token_count != expected_tokens:
            raise RuntimeError(
                f"Expected {expected_tokens} patch tokens, received {token_count}."
            )
        x = tokens.transpose(1, 2).reshape(
            batch_size, embed_dim, self.patch_grid, self.patch_grid
        )
        x = self.act(self.bn(self.proj(x)))
        return F.interpolate(
            x,
            size=(self.target_size, self.target_size),
            mode="bilinear",
            align_corners=False,
        )


class ParallelConvBlock(nn.Module):
    def __init__(self, in_channels: int, branch_channels: int = 64):
        super().__init__()
        self.conv3 = nn.Conv2d(in_channels, branch_channels, kernel_size=3, padding=1)
        self.conv5 = nn.Conv2d(in_channels, branch_channels, kernel_size=5, padding=2)
        self.conv7 = nn.Conv2d(in_channels, branch_channels, kernel_size=7, padding=3)
        self.act = nn.ReLU(inplace=True)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return torch.cat(
            [self.act(self.conv3(x)), self.act(self.conv5(x)), self.act(self.conv7(x))],
            dim=1,
        )


class ConvBlock(nn.Module):
    def __init__(self, in_channels: int, out_channels: int, pool: bool = True):
        super().__init__()
        self.conv = nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1)
        self.bn = nn.BatchNorm2d(out_channels)
        self.act = nn.ReLU(inplace=True)
        self.pool = nn.MaxPool2d(2) if pool else nn.Identity()

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.pool(self.act(self.bn(self.conv(x))))


class Stage2CNNHead(nn.Module):
    def __init__(self, in_channels: int, num_classes: int):
        super().__init__()
        self.parallel = ParallelConvBlock(in_channels, branch_channels=64)
        self.block1 = ConvBlock(192, 256, pool=True)
        self.block2 = ConvBlock(256, 512, pool=True)
        self.block3 = ConvBlock(512, 512, pool=False)
        self.flatten = nn.Flatten()
        self.fc1 = nn.Linear(512 * 4 * 4, 512)
        self.fc2 = nn.Linear(512, 128)
        self.out = nn.Linear(128, num_classes)
        self.dropout = nn.Dropout(0.5)
        self.relu = nn.ReLU(inplace=True)

    def forward(self, x: torch.Tensor, debug: bool = False) -> torch.Tensor:
        x = self.parallel(x)
        x = self.block1(x)
        x = self.block2(x)
        x = self.block3(x)
        x = self.flatten(x)
        if x.shape[1] != 8192:
            raise RuntimeError(f"Expected flatten size 8192, received {x.shape[1]}.")
        x = self.dropout(self.relu(self.fc1(x)))
        x = self.relu(self.fc2(x))
        return self.out(x)


class Stage2Model(nn.Module):
    def __init__(self, config: Stage2Config):
        super().__init__()
        self.cfg = config
        self.encoder = ViTEncoder(config.vit_name)
        self.cba = CBABlock(config.embed_dim)
        self.bridge = SpatialBridge(
            config.embed_dim,
            config.proj_channels,
            config.patch_grid,
            config.spatial_target,
        )
        self.head = Stage2CNNHead(config.proj_channels, config.num_classes)

    def forward(self, x: torch.Tensor, debug: bool = False) -> torch.Tensor:
        tokens = self.encoder(x)
        tokens = self.cba(tokens)
        spatial = self.bridge(tokens)
        return self.head(spatial, debug=debug)


def create_model(num_classes: int = 9, checkpoint_config: dict[str, Any] | None = None) -> Stage2Model:
    """Create the exact Stage-2 architecture used by the uploaded notebook."""
    values: dict[str, Any] = dict(checkpoint_config or {})
    allowed = {field.name for field in Stage2Config.__dataclass_fields__.values()}
    values = {key: value for key, value in values.items() if key in allowed}
    values["num_classes"] = num_classes
    return Stage2Model(Stage2Config(**values))
